### ISSUE TITLE
Need assistance for the partition of the sdcard and booting after that, also there is an format execution error while installing the custom on the board.

### ISSUE THREAD

**Issue by DSatle** [andre1araujo/YOLO-on-PYNQ-Z2#1]
Hello Andre I am following this repo for implementation of YOLO on PYNQ Z2 board. Sir I am facing following issues

1. When I am partitioning the SD card, I am not able to boot the board using the SD card. I am using Mobaxterm for accessing the board. I am following the same steps mentioned by you in the repo kindly help me on that.
2. Sir, since I am not able to do partition I have burned the image file on the SD card, and since the image file is based on the ubuntu I tried cloning the custom IP on the board through GitHub, which was successful but the issue is when I am trying to install the custom IP using the install.sh file I am not able to install the IP it shows format execution error, I am attaching the screenshot of the same. 
3. Apart from this I am also facing issue while dedicating the IP for accessing the internet on the board, if possible kindly share any contact info of yours so that I can contact you if I face any further issues for the same.
![Fomat_error_PYNQ](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/140998466/0a49ea59-da73-4934-9b73-4350c73c8bf6)
![format_error_PE](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/140998466/50e670d0-6705-4f9c-b593-8f6c608aefdb)

**Comment by andre1araujo** [comment]
Hello sir!

About the **first issue**, I will need more details to identify the problem. What I can suggest for now is to format the SD card before partitioning. Also make sure the `image.ub` and `BOOT.bin` files are on the "BOOT" partition and the `rootfs.tar.gz` on the "rootfs" partition. Verify if the names are correct.

On the **second issue** I am not entirely sure what do you mean when you say "I tried cloning the custom IP on the board through GitHub". Are you refering to [this](https://github.com/Xilinx/DPU-PYNQ)? If you are, I am sorry but you cannot install the DPU overlay that way. That DPU is a earlier one so it is not designed for the PYNQ-Z2. The DPU version 3.0 was the one I used and it was embeded on the custom SD card image.
Still, I am not sure what is causing the error for the installation script. It might just be because you cloned the other DPU IP and it is confused in some way. 
What I suggest for now is for you to download the SD card image I provided [here](https://drive.google.com/file/d/1ETyM51KSWX_h1DVq9ptHPIux89oTrNPy/view?usp=drive_link) and flash it on a SD card. Then you insert that SD card on the PYNQ-Z2 and follow these steps [here](https://andre-araujo.gitbook.io/yolo-on-pynq-z2/deployment-on-pynq-z2/board-setup). The SD card image already has the compatible DPU installed and some important packages selected. If you follow the tutorial everything should work! :)

**Third issue** is about the IP address for acessing the internet. I suspect that you connected the board directly to the PC just like on my tutorial. This by itself does not grant access to the internet unfortunatly. 
What you need to do instead is to **connect your board to your network router**. I am sure you have some ethernet ports on your router, so you connect the board to one of them. Then you need to know the IP address assigned to the board on the network so you have to look it up on the network configurations. You should have information written on the back of the router where you can access those configurations. Normally you just type `http://192.168.1.1` on your browser and you can access the configuration website. I attached a example screen shot so you can see how I can find the IP adress of the board:
![Pynq_Network_Connection](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/125664682/76a0f427-2f4c-4e2a-b069-2351aa36771e)


You should then try to access that adress trough MobaXterm.


If you have any more questions be sure to ask! You can contact me more privately on this email: a21185@alunos.ipca.pt. You can also contact me on linkedIn . My profile is available trough this [link](www.linkedin.com/in/andré-araújo-77a6882b0).

Thank you! I hope I could help! :)
