### ISSUE TITLE
Same model on zcu104

### ISSUE THREAD

**Issue by pramod627** [andre1araujo/YOLO-on-PYNQ-Z2#2]
Hi,
I have followed this project to implement yolo inference on pynqz2.
I want to implement the same on ZCU104. How can it be implemented?

**Comment by andre1araujo** [comment]
Hello!

I cannot give you exact details on how to proceed to implement something similar but on the ZCU104 board. I can, however, give you some guidelines on that regard.

First, you need to **create the DPU design for the ZCU104** . You can (and sohuld) use a **newer version and more powerful architecture of the DPU** since your board is a **Zynq UltraScale+ MPSoC**. This means that the ZCU104 has a lot more resources than the PYNQ-Z2 and that will allow you to make more demanding applications just like the YOLO Neural Network.
On this [link](https://docs.amd.com/r/4.0-English/pg338-dpu/Development-Flow), you have the documentation necessary to implement the DPU version 4.0 (second newest) for your board. Don't forget to use specifically **Vivado 2022.1** for implementing the DPU (you can see someone specified it on [this ](https://support.xilinx.com/s/question/0D54U00005UC3sHSAT/any-updated-document-or-git-hub-repo-that-explains-completely-how-to-run-pytorch-model-on-dpu-after-the-dpu-has-been-customized-and-a-new-xsa-file-has-been-generated-in-vivado?language=en_US)post). You should also find a lot of documentation to help you create that DPU on Vivado but also do the Petalinux part. I should say that the process is very well documented compared to a implementation for the PYNQ-Z2.

After the DPU design is done and **you have a micro SD card with that DPU**, it is time for the **host part**. On my tutorial I often refered to it as the "DNNDK" part but here is something different now. As your board can handle a better DPU, it needs to use a **newer host tool from xilinx, called Vitis AI**. You need to use Vitis AI to convert the YOLO model for a special file that interacts with the DPU (creating the desired Neural Network). 
Because you implement **DPU 4.0, you have to install Vitis AI version 2.5** as you can se from this table you can consult [here](https://xilinx.github.io/Vitis-AI/3.5/html/docs/reference/version_compatibility.html#version-compatibility):

![Vitis_AI_version](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/125664682/38f7c280-0d0f-49b8-b2b4-2e04e39e4a2c)

You can follow the instalation details from the Vitis Ai user guide: https://docs.amd.com/r/2.5-English/ug1414-vitis-ai/Getting-Started.
The guide is very well detailed and you should be able to follow it correctly. Also, do not forget that Vitis AI is compatible with these operating system: Ubuntu 18.04, 20.04(Linux kernel <=5.8). 

After the installation, you can implement the YOLO in a somewhat similar way to what I did. **Vitis AI has [this ](https://github.com/Xilinx/Vitis-AI-Tutorials/blob/1.3/Design_Tutorials/07-yolov4-tutorial/README.md)tutorial** on which they implement YOLOv4 on using the Vitis AI version 1.3. The process should be very similar. I also believe that there are a lot more tutorials available online, you just have to search for example on github! On your search you don't need to specify your board. It can be done for example on the ZCU102, the Kria SOM and a lot of other board that use the Zynq Ultrascale+ chip. Do not be afraid to try new implementations!

I hope this guidelines were helpfull for you! If you need any more assistance don't hesitate!

Good luck for your project! :)
