### ISSUE TITLE
A problem during Project configuration

### ISSUE THREAD

**Issue by menger02** [andre1araujo/YOLO-on-PYNQ-Z2#3]
Hello, I'm very sorry to disturb you. 
When I write petalinux-config -c rootfs ,it has the problem like this. Can you help me?
![I`EA0V(Z1@YO%XE02PND8GN](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/103489023/d771815a-f9d8-412b-aadc-0bd3b664d680)

**Comment by andre1araujo** [comment]
Hello!
You are not bothering at all. Fell free to ask any questions!

About the problem you are facing, it can be due to a lot of reasons. I suspect it is something simple. I looked at [this forum post](https://support.xilinx.com/s/question/0D52E00006hpWZjSAM/petalinux-error-failed-to-create-workspace-directory?language=en_US) where someone was having a similar error. If you scroll down, there is this response:

![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/125664682/7dc8bb8d-1150-4dba-8e03-8d88f7d34ccc)

What they suggest is that **there was a "CTRL+C" command** somewere alog the process. And according to your screenshot, you did exactly that. You can do what they say on the comment above (kill processes) or you could just **close petalinux or even restart Ubuntu and then open the Petalinux project again and execute the command you did**. If it does not work you could start the Petalinux project again and this time make sure to not "CTRL+C" in the middle of any process.

If that does not work, the **problem might be related with the permissions of the folder/ path** your project is located in. I don't think this is the problem but you could try the next command: `chmod 777 Desktop/dpu_integration/pynqz2_dpu`
This command gives read, write and execute permissions. 

I hope this helps! If the problem pressists be sure to come back to this post! 
If you are able to solve the problem, I request that you come back and tell us so that this post can be usefull to another person that might get stuck on the same problem!

**Comment by menger02** [comment]
Hello, thank you for your reply. But unfortunately, it's not as you said. Through the website you shared, I learned that the cause of the error can be understood through the build/config.log file. I found that the problem lies in the     echo 'IMAGE-INSTALL-append="dpu".     After changing it to    IMAGE-INSTALL-append="dpu", this error disappeared.
 But I encountered a new problem again, as shown in the second and third images. I guess it was caused by the colon after the DPU, but after I made the modifications, I found that it was not like this, and after running it, it changed to its previous appearance. Do you know the specific reason? Or is it that my previous modifications were not correct?
![FX6{DIXWVF83L}RU$XNQ}IN](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/103489023/df40f3fd-bf17-45ef-975f-d7f17e54ba70)
![MK73CTC2)E0 $PY A216_SG](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/103489023/d96b2c2a-3a16-4822-ad0f-fb1964c247da)
![(3Q_~ W D)ZVR3OXAA41T~0](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/103489023/34575805-d638-42e0-81c4-9e68047cc551)

**Comment by menger02** [comment]
> Hello! You are not bothering at all. Fell free to ask any questions!
> 
> About the problem you are facing, it can be due to a lot of reasons. I suspect it is something simple. I looked at [this forum post](https://support.xilinx.com/s/question/0D52E00006hpWZjSAM/petalinux-error-failed-to-create-workspace-directory?language=en_US) where someone was having a similar error. If you scroll down, there is this response:
> 
> ![image](https://private-user-images.githubusercontent.com/125664682/323239115-7dc8bb8d-1150-4dba-8e03-8d88f7d34ccc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzI4ODksIm5iZiI6MTcxMzQzMjU4OSwicGF0aCI6Ii8xMjU2NjQ2ODIvMzIzMjM5MTE1LTdkYzhiYjhkLTExNTAtNGRiYS04ZTAzLThkODhmN2QzNGNjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQwOTI5NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzI5OTNiMDQ1YTEzNWE4NGVjOWQ1NjZjNDhiZDk3M2ViYmEwZjg2M2FiYmRkYjY0YTI5NmUzNjhjNWI5MDE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._35AHgTJ9sxlX-wM7axB2CoYmeOALzcIELov3TWsVCc)
> 
> What they suggest is that **there was a "CTRL+C" command** somewere alog the process. And according to your screenshot, you did exactly that. You can do what they say on the comment above (kill processes) or you could just **close petalinux or even restart Ubuntu and then open the Petalinux project again and execute the command you did**. If it does not work you could start the Petalinux project again and this time make sure to not "CTRL+C" in the middle of any process.
> 
> If that does not work, the **problem might be related with the permissions of the folder/ path** your project is located in. I don't think this is the problem but you could try the next command: `chmod 777 Desktop/dpu_integration/pynqz2_dpu` This command gives read, write and execute permissions.
> 
> I hope this helps! If the problem pressists be sure to come back to this post! If you are able to solve the problem, I request that you come back and tell us so that this post can be usefull to another person that might get stuck on the same problem!

Hello, thank you for your reply. But unfortunately, it's not as you said. Through the website you shared, I learned that the cause of the error can be understood through the build/config.log file. I found that the problem lies in the echo 'IMAGE-INSTALL-append="dpu". After changing it to IMAGE-INSTALL-append="dpu", this error disappeared.
But I encountered a new problem again, as shown in the second and third images. I guess it was caused by the colon after the DPU, but after I made the modifications, I found that it was not like this, and after running it, it changed to its previous appearance. Do you know the specific reason? Or is it that my previous modifications were not correct?
![FX6{DIXWVF83L}RU$XNQ}IN](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/103489023/84c4aa48-d121-421d-908f-b5e89ec5c835)
![MK73CTC2)E0 $PY A216_SG](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/103489023/fe8ae1af-45a1-4d85-80fc-8174722aad2b)
![(3Q_~ W D)ZVR3OXAA41T~0](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/103489023/bb55544b-46f8-47f7-a197-afaff5579693)

**Comment by andre1araujo** [comment]
Hi again!

I don't know the specific problem. Can you make sure you wrote `echo 'IMAGE_INSTALL_append = "dpu"'`, with the apostrophe at the begining of "IMAGE" and at the end of "dpu"? Also, notice that it is using underscore: "_" and not hyphen: "-". Just copy and paste the command as is.
I don't see the reason this is not working. It should be something about spelling or some step that was not followed correctly.

I hope this helps! Write back if you find anything else or if the problem presists!
