### ISSUE TITLE
Issue with Petalinux.

### ISSUE THREAD

**Issue by Schrodingerrs-cat** [andre1araujo/YOLO-on-PYNQ-Z2#6]
Hi Andre,
I am currently following your tutorial on GitBook to learn more about implementing Machine Learning on FPGA. I have reached the section titled "Implementing DPU on SD card" and encountered some difficulties progressing beyond this point. I have successfully completed all the previous steps correctly.

I am stuck at the step where it states: "On the final part, you have to place the path to the '.xsa' file... You will be presented with a nice little menu. Here is how you can work on this configuration interface." Below is the terminal log from my session:

`
aryan@petalinux:~$ cd pynqz2_dpu/
aryan@petalinux:~/pynqz2_dpu$ source /opt/petalinux/settings.sh
PetaLinux environment set to '/opt/petalinux'
INFO: Checking free disk space
INFO: Checking installed tools
INFO: Checking installed development libraries
INFO: Checking network and other services
WARNING: No tftp server found - please refer to "PetaLinux SDK Installation Guide" for its impact and solution
aryan@petalinux:~/pynqz2_dpu$ petalinux-create --type project --template zynq --name pynqz2_dpu
INFO: Create project: pynqz2_dpu
INFO: New project successfully created in /home/aryan/pynqz2_dpu/pynqz2_dpu
aryan@petalinux:~/pynqz2_dpu$ cd pynqz2_dpu/
aryan@petalinux:~/pynqz2_dpu/pynqz2_dpu$ petalinux-config --get-hw-description=/home/aryan/Desktop/oynqz2_dpu
INFO: Getting hardware description...
INFO: Rename pynqz2_dpu.xsa to system.xsa
[INFO] generating Kconfig for project
[INFO] menuconfig project
ERROR: Failed to menu config project component
ERROR: Failed to config project.
ERROR: Get hw description Failed!.
aryan@petalinux:~/pynqz2_dpu/pynqz2_dpu$
`

I am unsure why these errors are occurring. Could you help me identify any potential mistakes I might have made?

**Comment by andre1araujo** [comment]
Hello Shah Aryan!
First of all, sorry for the late response. I am answering the question here because it might help other people.
I am sorry you encountered that error. I was already looking for the problem online and was thinking it could be to version mismatch but I think I fount your problem. Take a look at the way you wrote the command:

![Petalinux_Problem](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/125664682/c7c94785-b927-4d35-8bf1-5ce569c6b104)

As you can see, you put a "o" instead of a "p". It happens to the best of us ;)
Let me know if that was the problem and don't hesitate in writting back to let me know!
Good luck for your project! :)

**Comment by Schrodingerrs-cat** [comment]
Hi Andre,

Thank you for your reply. I apologize for any confusion caused. The folder name "oynq" is actually correct, as I mistakenly named it that way, and I neglected to specify this in the issue. The 'o' is correct, as I've named the folder as that. I am sorry for that. So the problem still pertains unfortunately.

You mentioned a potential version mismatch. Could you please clarify which versions I should be using? I have been following the versions specified in your tutorial. Should I consider using different versions?

Additionally, what other possible issues could be causing the errors I'm encountering?

**Comment by andre1araujo** [comment]
Hi again Aryan!
Well, I believe you have everything right then. I suspect it is something simple. So, based on the commands you sent me, try to see if there is another "pynqz2_dpu" folder inside the "pynqz2_dpu" folder on the Desktop.
If that is the case, I think you will have to do the command like this:
`petalinux-config --get-hw-description=/home/aryan/Desktop/pynqz2_dpu/pynqz2_dpu`
Before that, don't forget to execute `source /opt/petalinux/settings.sh`
Try to see if this works.
Reach back to me if the problem presists!
Good luck!

**Comment by Schrodingerrs-cat** [comment]
I have to give the path to the XSA file there right? The xsa file is inside
the folder "pynq_dpu" (or oynq_dpu as I've named it)that is on the desktop. Petalinux only
requires the .xsa file right for this operation?

Also you can check the log that its renaming the .xsa file to something
else and then the errors are coming. So far I've tried reinstalling the
Petalinux, checking and verifying the DPU IP again and again. I couldn't
figure where I'm making a mistake.

Do you know any alternative, so I can convert this .xsa file into a
bootable file with the required libs , in case this issue doesn't get
resolved?

**Comment by andre1araujo** [comment]
Well, if everything goes wrong, you can just download the SD card image file [here](https://drive.google.com/file/d/1ETyM51KSWX_h1DVq9ptHPIux89oTrNPy/view) and flash it on the micro SD card, following [this part](https://andre-araujo.gitbook.io/yolo-on-pynq-z2/requirements#if-you-just-want-to-execute-the-yolo) of the tutorial.
The SD card image has the process you are doing already finished. Also, you can try to restart the Petalinux process and use my .xsa file I provided [here](https://drive.google.com/drive/u/2/folders/1zjT3rumAlyVTswpLKu8xpxo4e379B1a2) and see if that solves the problem.
I can try and look more into that problem but I don't have much experience with Petalinux. I followed the tutorial presented somewhere else. 
Just do not worry to much because the SD card image has everything ready! :)

**Comment by MaRcOsss1** [comment]
Hey, sure I'll try that and let you know. Anyways you can see in my log
that there's a warning " WARNING: No tftp server found". So I looked on
Xilinx support documents and it said:
[image: image.png]
Do you have any idea what this is about?

**Comment by Schrodingerrs-cat** [comment]
Hey, sure I'll try that and let you know. Anyways you can see in my log that there's a warning " WARNING: No tftp server found". So I looked on Xilinx support documents and it said:
![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/123965986/149f53c7-7c9e-476e-9edc-93146adc8cd9)
Do you have any idea what this is about?

**Comment by andre1araujo** [comment]
Hi!
No, I don't really know what that is all about but you can just ignore it. It is not usefull for our application.
On that description it mentions Microblaze. Microblaze is basically a microprocessor made in the FPGA. It is Xilinx property and it is more usefull for raw FPGA boards, unlike the PYNQ-Z2 that uses the FPGA and a ARM cortex A9 processor separatly (SoC - System on Chips).

**Comment by Schrodingerrs-cat** [comment]
Hey Andre I tried running your .XSA file in the petalinux but I ran into more errors. You can see the last part of log here:

aryan@petalinux:~/Desktop/dpu_integration/pynqz2_dpu$ petalinux-config --get-hw-description=/home/aryan/Desktop/pynqz2_dpu
INFO: Getting hardware description...
INFO: Rename pynqz2_dpu.xsa to system.xsa
[INFO] generating Kconfig for project
ERROR: [HDF 64-4] /home/aryan/Desktop/dpu_integration/pynqz2_dpu/project-spec/hw-description/system.xsa is not valid Hardware Handoff File
ERROR: [Hsi 55-1451] Error: running open_hw_design.
ERROR: Failed to generate /home/aryan/Desktop/dpu_integration/pynqz2_dpu/build/misc/config/Kconfig.syshw
ERROR: Failed to Kconfig project
ERROR: Failed to generate System hardware Kconfig file.

**Comment by andre1araujo** [comment]
Hello!
It's weird it does not recognise the file. Obviously it worked for me back then. Try to use this one here. I had this one still in my Virtual Box environment so it should work. Let me know if it works!
[pynqz2_dpu_xsa.zip](https://github.com/user-attachments/files/15955295/pynqz2_dpu_xsa.zip)

**Comment by Schrodingerrs-cat** [comment]
Hey Andre,
Its still not working, I wanted to learn the process but I think something's wrong with my petalinux or ubuntu. I am not sure whats the issue, do you know any alternate method I can use to turn my .xsa into or to generate  bootable image files other than petalinux?

Log:
aryan@petalinux:~/pynqz2_dpu1$ petalinux-config --get-hw-description=~/
INFO: Getting hardware description...
INFO: Rename pynqz2_dpu.xsa to system.xsa
[INFO] generating Kconfig for project
[INFO] menuconfig project
ERROR: Failed to menu config project component 
ERROR: Failed to config project.
ERROR: Get hw description Failed!.

![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/123965986/9a763406-72d3-417f-bb50-4cb0439785cb)
![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/123965986/ca6acb0b-3d51-46de-9a84-1b8e4bae85c4)

**Comment by andre1araujo** [comment]
Hello Aryan!
I don't think there is an alternative method for turning the Hardware design into a bootable SD card image. 
I think you can try one last thing, that is, instead of writting the path to the .xsa file, you write the path to the whole Vivado project. Could you do that? Bring all the files to Ubuntu and serve the corresponding path.
Let me know if that works because I find this all very suspicious since the specs are the same according to the tutorial I built.
Again, I am sorry for the inconvenience and I hope I could help.
Good luck!

**Comment by Schrodingerrs-cat** [comment]
Hey Andre, Don't be sorry its not your fault, you have helped as much as you can from your end. I appreciate you giving efforts in solving my problem.

So all the vivado project files are already on the VM, and thats what I was doing till now, giving path to the whole folder which included my complete Vivado Project.
![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/123965986/29f5e701-2928-4ed2-b456-29f975c53ec8)

I'll try doing that with your files, once and I will let you know.

Also I had posted the same query on Xilinx Forum and this is the response: ![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/123965986/7fd19196-cdba-40de-a627-a7a5e65ea8c4) 
Do you have any idea regarding "supported host machine"? Is he referring to VM?

**Comment by andre1araujo** [comment]
Hello!
The host machine is a reference to the Software you are using on the Virtual Machine. In your case it should be Ubuntu 18.04. On the user guide it says it only supports Ubuntu 18.04 or 16.04 if I am not mistaken. 
Then there is the Petalinux version which should also be compatible with the Vivado version.
Hope this helps!

**Comment by Schrodingerrs-cat** [comment]
Hey Andre,
I have disturbed you enough with petalinux but this is something I had to tell you, so as I said I was so done with the petalinux and the errors. So I deleted the petalinux compeletely, and downloaded the petalinux again, with its supported files and packages and I thought to give it a one last try following the tutorial, and guess what? It worked, no errors.  I can continue learning the process finally. I wish I had deleted the petalinux and re-download it from scratch without wasting days behind this.

I am so sorry taking so much of your time and I am thankful to help me the best you can, You are really the best.

Also for [this](https://andre-araujo.gitbook.io/yolo-on-pynq-z2/model-optimization-and-compilation) part of the tutorial , I have to Dual boot my PC right?

**Comment by andre1araujo** [comment]
Hello Aryan!
That's a classisc engineer move haha. I am glad it worked. Sometimes we miss some details along the process and that is why your feedback is important: so I can correct the tutorial and give new guidelines to the readers.
Sorry again I could not help perfectly!

About the Dual Boot, that is correct. The DNNDK tool is only supported in Ubuntu 16.04 or Ubuntu 18.04 (according to the user guide of course). If you have those versions of Ubuntu on a different computer you can use it but most people have Windows or a more recent version of Ubuntu so Dual Boot is necessary. 
I ended up not including the dual boot process on the tutorial because it can vary a little bit for each PC and I wouldn't want the responsibility if it went wrong. But there are plenty of tutorials online! Just be sure to make a copy of the most important files in case you lose the Windows partition by mistake.
Good luck with the rest of the process! Be sure to report any questions or problems you encounter! :)

**Comment by Schrodingerrs-cat** [comment]
Hey Andre,
I am not going to stop disturbing you until this project is over haha. I ran into porblem again I dont know what happened. So I have used the P7zip , copied the recipe modules, and tried to run `petalinux-config -c rootfs` but ran into the error : `ERROR: Failed to create workspace directory
ERROR: Failed to config rootfs.`

And I have followed your tutorial line to line, step by step, I am doing nothing different. I had run this command before and it worked then, since then its not working, I had repeated all the steps from scratch and made a new folder but its not working.


The log:
![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/123965986/787b4863-50b2-461c-9faa-30a8eab932c1)
![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/123965986/72193a04-2822-4f05-9977-5b41f8f40083)

**Comment by andre1araujo** [comment]
Hello!
I don't know why it failed but generally is because something is missing. Or because you are unlucky haha.
Anyway, did you do this part?

![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/125664682/6a79bf10-aa62-4fd3-a769-62e83bf89214)

Find that specific file and add this `echo 'IMAGE_INSTALL_append = "dpu"'` on the last line of the document.

![conf_file](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/125664682/8be6c642-f468-41bd-9d0f-ce156ff456fa)

If that was done, confirm that the files are on the correct place. Check these screenshots to see if the project organization is the same. I noticed the tutorial is quite confusing and should have some checkpoints to make sure the reader has everything together.

![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/125664682/f803f334-2784-4acb-a2a5-943b1be6051e)

If any of these sugestions work, let me know. Otherwise it might be something more complicated.
Good luck!

**Comment by Schrodingerrs-cat** [comment]
I dont have the 2 .bsp files you have in this folder, can that be a problem?
![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/123965986/63bf8daf-56f8-46b9-82ad-5be8f9505c90)
I dont seem to have recipes-kernel here...why is that? I copied the recipe modules already?
![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/123965986/5c9297bb-3165-47c2-a1a0-000d91eaffd2)

**Comment by andre1araujo** [comment]
I don't think those files are the problem because they probably were product of future steps. Still, I am not sure.
Try to restart the petalinux project. Close the VM and do `cd Desktop/dpu_integration/pynqz2_dpu` and `source /opt/petalinux/settings.sh`. Then do the `petalinux-config -c rootfs` again to see if works now. Sometimes if you inturrupt a process, it leaves some background tasks running. If the error pressists try to look on the log file to identify the error!
Good luck!

**Comment by Schrodingerrs-cat** [comment]
haha Dude your'e the best , it worked, I restarted the VM and it worked, Thanks a lot, will go ahead with the next step now haha.

**Comment by andre1araujo** [comment]
Let's go! Let me know if there are any further issues!

**Comment by yolovino1** [comment]
hello, Andre,I'm trying run your peoject ,but I'm having problem with the problem which keeps loading petalinux-config -c kernel but nothing happens. Does this program take so long to load, or is there something wrong with my other settings?
<img width="891" alt="Pasted Graphic 12" src="https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/167788524/1e1036f9-6268-4f5b-a944-0978d3e700a3">
 
<img width="894" alt="Pasted Graphic 14" src="https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/167788524/21fede4f-de45-4e84-b44f-cfae5e9e86e1">

I followed your idea and set it up, but it still doesn't work.
<img width="702" alt="Pasted Graphic 15" src="https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/167788524/3d329478-b45f-40c2-824e-504aeda87e95">

**Comment by yolovino1** [comment]
<img width="892" alt="Pasted Graphic 16" src="https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/167788524/93792336-b51c-44a6-8bbf-960062a78479">

it works successful without realizing it

**Comment by yolovino1** [comment]
<img width="663" alt="Pasted Graphic 17" src="https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/167788524/ac649288-b4bb-4b42-a892-3d065af827c3">

something went wrong again

**Comment by andre1araujo** [comment]
> <img alt="Pasted Graphic 17" width="663" src="https://private-user-images.githubusercontent.com/167788524/344063278-ac649288-b4bb-4b42-a892-3d065af827c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NzIxMTAsIm5iZiI6MTcxOTU3MTgxMCwicGF0aCI6Ii8xNjc3ODg1MjQvMzQ0MDYzMjc4LWFjNjQ5Mjg4LWI0YmItNGI0Mi1hODkyLTNkMDY1YWY4MjdjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOFQxMDUwMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTRjNDY0Mzk1ZmM2ZDVlYjc1NjVmOTMxMzNlMjUzMmY5ZDNmOGNlMjJmNGI4YjhkZmNkNjRhY2I0Y2E5MmNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pbybpEKTxk54fovplharslwt-M394O2aPhccSa7dmas">
> something went wrong again

Hello!
Can you specify the problem you are having? It looks like the file `devtool-fragment.cfg` exists there and you already pasted the code specified on the tutorial, even though you have the warning on top. Did you do the `petalinux-build` command after? Did it provide any errors?
I need more information so I can try to help :)

**Comment by yolovino1** [comment]
Thank you for your reply. I haven't executed the petalinux build command yet because the gedit project spec/meta user/recipes kernel/Linux/Linux xlnx/devtool fragment. cfg command couldn't pass. When I went to the file, I saw that I don't have the recipes kernel file below. I saw the question above. You mentioned restarting the virtual machine without the recipes kernel, cd Desktop/dpu_integration/pnqz2udpu, and source/opt/petalinux/settings. sh. Then execute petalinux config - c rootfs again, and I have executed all of them
![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/167788524/d029227e-84a1-4cbc-8fa4-7ddcc37ac260)
It's just my sixth attempt at petalinux config - c kernel，
![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/167788524/bc578edb-1c72-4b20-85d4-a1d3c37797d1)

![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/167788524/9963cbf3-165d-482b-aa1b-00ada9b79634)
And I don't know exactly how to do this step and then enable it: Device Driver ->USB Support ->[*] USB Announce New Device

**Comment by yolovino1** [comment]
![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/167788524/6dd2674e-312f-4f93-b534-402b46f84b5d)

![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/167788524/b0bd5d58-df32-4438-b9a8-bce604fae1e7)

![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/167788524/a5cd25a0-72c5-4b9c-81bd-f57f1da508d3)

![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/167788524/a6923211-d6d5-4d02-9595-037ec8abc335)

DTG settings ->kernel startup parameters ->disable automatic generation of startup parameters, and there is no disable for automatic generation of startup parameter selection


![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/167788524/59b9dcab-29e8-4340-8dd4-15651823d57c)
There is no module ->DPU selection here

**Comment by andre1araujo** [comment]
Okay, I think you forgot to start up Petalinux correctly again.
You restart the Virtual Machine, do `cd Desktop/dpu_integration/pnqz2_dpu` and then `source /opt/petalinux/settings.sh`. This last command is very important and you have to do it everytime you restart the project because it starts the Petalinux correctly.
After that, its better to start the process again just to make sure everything is correct. 
As for your last comment, if there is no DPU selection, I think its better to start again. Do these:
- Delete the project folder "dpu_integration"
- Create the folder again with the same name on the Desktop
- Access the folder on the Terminal using `cd Desktop/dpu_integration`
- Activate Petalinux with `source /opt/petalinux/settings.sh` command
- Create the project based on the zynq template: `petalinux-create --type project --template zynq --name pynqz2_dpu`
- Open the newly created project: `cd pynqz2_dpu/`
- Base the project on the DPU hardware created in Vivado using `petalinux-config --get-hw-description=/home/user/Desktop/VivadoDPU/pynqz2_dpu` (Assuming you have the Vivado project on the Desktop with the name VivadoDPU)
- Then you do this part:

![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/125664682/71966ca9-b7b3-4847-9f22-c119b9ebddcf)

Continue the rest of the tutorial from there and it should work. I really think the problem was that after you restarted you did not activate Petalinux with `source /opt/petalinux/settings.sh`.
Just make sure you follow the start and then let me know ehat problems you encounter!
I am sorry for the inconvenience.

**Comment by yolovino1** [comment]
OK， I followed your instructions and did the following,
![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/167788524/75786571-ae5e-4a4f-a104-77
![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/167788524/5c08efcc-2bb2-41c0-be3a-764ff095ba31)
![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/167788524/78fd2728-3725-4171-83d5-4907fd03edcc)
在DTG Settings+Kernel Bootargs -disable generate boot args automaticallyI didn't see anything in heredisable generate boot args 
Automatically options, or Where do I need to go to set this to disable automatic generation of startup parameters
![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/167788524/31bcc2a8-c462-48cc-85d0-9f616541977a)

**Comment by andre1araujo** [comment]
Press `ENTER` on "kernel bootargs" and then press `"n"` to disable "generate bootargs automaticaly". When I say enable you press "y", and disable you press "n". Can you do that?

**Comment by yolovino1** [comment]
It's not like that, when you press kernel bootars,
![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/167788524/54f43d71-e247-47f3-b9fe-613708b20688)

What appears is the image below, without the option to generate bootars automatically
![image](https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/167788524/b3e3eeee-c14c-4ee0-92cf-02bdf989d2e5)

**Comment by andre1araujo** [comment]
Hi! Sorry for the delay response. That is not usual what you are encountering. Do you have the correct Petalinux version? Is the vivado project correct? You can try with my vivado project and see if it works now. It can be downloaded [here](https://drive.google.com/drive/u/2/folders/1Tga_d2qfZRlQrvJvwPAHon4qpM60h9UP).
Good luck! Let me know if you got it working!

**Comment by yolovino1** [comment]
Replace my file with yours，The following issue has occurred. My model is zynq7020, and I have checked the configuration settings according to my board's settings. The DDR3 model is NT5CC256M16,
Parts, select "clg400" in the Package column
XC7Z020 speed is -2
xc7z020clg400-2”，你的好像是7010的，speed is -1 ,
<img width="908" alt="image" src="https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/167788524/bf70e38a-48cd-4833-a330-8773eaaac446">

 Petalinux version is 2019.2，vivado is base on you intruction 
<img width="168" alt="image" src="https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/167788524/396fca99-8cc0-4b0e-9111-174c51e4fe06">

<img width="430" alt="image" src="https://github.com/andre1araujo/YOLO-on-PYNQ-Z2/assets/167788524/668e3e24-83cc-4c3e-9317-d369c9b572bf">

**Comment by andre1araujo** [comment]
I don't see a reason why that is not working then. Even if your board is different than PYNQ-Z2, the project does not care about it since you are using the zynq template on Petalinux. 
It is weird it is not recognising the project I sent you because it worked for me obviously.
Unfortunatly I don't know how I can helo you with this. All I can say is to try again, not forgeting to do the command `source /opt/petalinux/settings.sh` to start Petalinux. 
I am really sorry for the inconvenience. I hope you can reach the solution. In any case, report back to me when you try something else or get any progress!

**Comment by yolovino1** [comment]
拥有pynq-z2-dpu.bsp是否可以跳过这个过程，我在GitHub文件找不到你发的文件里面包含pynq-z2-dpu.bsp

**Comment by yolovino1** [comment]
Can I skip this process if I have pynq z2 dpu.bsp? I couldn't find the file you sent in the GitHub file, which contains pynq z2 dpu.bsp

**Comment by MaRcOsss1** [comment]
Hey Andre, I had a doubt regarding Model Conversion. I am trying to use Mobile net trained model, which is already based on Tensorflow, Do I need to undergo model conversion for that? I dont think I should , under that case what could be my next step?

**Comment by MaRcOsss1** [comment]
Hey Andre, I had a doubt regarding Model Conversion. I am trying to use Mobile net trained model, which is already based on Tensorflow, Do I need to undergo model conversion for that? I dont think I should , under that case what could be my next step? Should I move to quntization?

**Comment by andre1araujo** [comment]
I am not sure it will be enough to skip the process. I will send you the .bsp file anyway.
Hope it helps. Let me know! 
[pynq-z2-dpu.zip](https://github.com/user-attachments/files/16072673/pynq-z2-dpu.zip)
